/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package dostavljanjeposiljke;

import controller.Controller;
import domain.DostavniSpisak;
import domain.PostanskiRadnik;
import domain.Razduzuje;
import domain.Uplata;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import session.LocalStorage;
import tableModels.UplataPosiljkeTableModel;

/**
 *
 * @author Vuk
 */
public class PredajaNovca extends javax.swing.JDialog {

    /**
     * Creates new form PredajaNovca
     */
    private final LocalStorage localStorage = LocalStorage.getInstance();
    private List<Uplata> uplate;
    private final DostavniSpisak dostavniSpisak;
    private final PostanskiRadnik postar;
    private final PostanskiRadnik obracunskiRadnik;
    private final Razduzuje razduzuje;
    
    public PredajaNovca(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        dostavniSpisak = (DostavniSpisak) localStorage.getItemFromHashMap("dostavniSpisak");
        postar = (PostanskiRadnik) localStorage.getItemFromHashMap("postanski-radnik");
        obracunskiRadnik = dostavniSpisak.getObracunskiRadnik();
        razduzuje = new Razduzuje(obracunskiRadnik, postar, 0);
        setComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPostar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtObracunskiRadnik = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblIsplatePosiljki = new javax.swing.JTable();
        btnPredajaNovca = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Predaja novca");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Poštar");

        txtPostar.setEditable(false);
        txtPostar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Obračunski radnik");

        txtObracunskiRadnik.setEditable(false);
        txtObracunskiRadnik.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel4.setText("Isplate primljenih pošiljki");

        tblIsplatePosiljki.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblIsplatePosiljki);

        btnPredajaNovca.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnPredajaNovca.setText("Predaja novca");
        btnPredajaNovca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPredajaNovcaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtObracunskiRadnik, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                            .addComponent(txtPostar))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(btnPredajaNovca, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPostar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtObracunskiRadnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPredajaNovca, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPredajaNovcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPredajaNovcaActionPerformed
        // TODO add your handling code here:
        Integer ukupanNovac = sumOfAllPayment();
        razduzuje.setIznos(ukupanNovac);
        String messageException;
        try {
            messageException = Controller.getInstance().addRazduzuje(razduzuje);
            if(messageException==null){
                JOptionPane.showMessageDialog(this, "Uspešno prebacivanje novca");
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, messageException, "Exception", JOptionPane.PLAIN_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Exception", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_btnPredajaNovcaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPredajaNovca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblIsplatePosiljki;
    private javax.swing.JTextField txtObracunskiRadnik;
    private javax.swing.JTextField txtPostar;
    // End of variables declaration//GEN-END:variables

    private void setComponents() {
        txtPostar.setText(postar.getImePrezime());
        txtObracunskiRadnik.setText(obracunskiRadnik.getImePrezime());
        populateTable();
    }

    private void populateTable() {
        try {
            List<Uplata> allUplate = Controller.getInstance().getUplate(new Uplata());
            uplate = allUplate.stream().filter(upl -> upl.getPosiljka().getVreca().equals(dostavniSpisak.getVreca()))
                                       .collect(Collectors.toList());
            tblIsplatePosiljki.setModel(new UplataPosiljkeTableModel(uplate));
        } catch (Exception ex) {
            Logger.getLogger(PredajaNovca.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private Integer sumOfAllPayment() {
        return uplate.stream().mapToInt(upl -> upl.getUplatnica().getIznos()).sum();
    }
}
