/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package korisnik;

import domain.Korisnik;
import korisnik.posiljka.Posiljke;
import login.KorisnikLogin;
import session.LocalStorage;

/**
 *
 * @author Vuk
 */
public class KorisnikMain extends javax.swing.JDialog {

    /**
     * Creates new form KorisnikMain
     */
    private LocalStorage localStorage = LocalStorage.getInstance();
    private Korisnik korisnik;
    
    public KorisnikMain(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        lbImePrezime = new javax.swing.JLabel();
        lbTelefon = new javax.swing.JLabel();
        lbAdresa = new javax.swing.JLabel();
        lbGrad = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        miPrimljenePosiljke = new javax.swing.JMenuItem();
        miPoslatePosiljke = new javax.swing.JMenuItem();

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbImePrezime.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lbImePrezime.setText("jLabel1");

        lbTelefon.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbTelefon.setText("Telefon:");

        lbAdresa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbAdresa.setText("Adresa:");

        lbGrad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbGrad.setText("Grad:");

        btnLogOut.setText("<-] Odjavite se");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        jMenu4.setText("Pošiljke");

        miPrimljenePosiljke.setText("Primljene");
        miPrimljenePosiljke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPrimljenePosiljkeActionPerformed(evt);
            }
        });
        jMenu4.add(miPrimljenePosiljke);

        miPoslatePosiljke.setText("Poslate");
        miPoslatePosiljke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPoslatePosiljkeActionPerformed(evt);
            }
        });
        jMenu4.add(miPoslatePosiljke);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbImePrezime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTelefon, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(lbAdresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbGrad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lbImePrezime)
                .addGap(18, 18, 18)
                .addComponent(lbTelefon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbAdresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbGrad)
                .addGap(44, 44, 44)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        KorisnikLogin kl = new KorisnikLogin(null, true);
        localStorage.removeItemFromHashMap("korisnik");
        this.dispose();
        kl.setLocationRelativeTo(null);
        kl.setVisible(true);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void miPoslatePosiljkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPoslatePosiljkeActionPerformed
        // TODO add your handling code here:
        localStorage.addItemsInHashMap("tipKorisnika", "Posiljalac");
        Posiljke pp = new Posiljke(null, true);
        pp.setLocationRelativeTo(null);
        pp.setVisible(true);
    }//GEN-LAST:event_miPoslatePosiljkeActionPerformed

    private void miPrimljenePosiljkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPrimljenePosiljkeActionPerformed
        // TODO add your handling code here:
        localStorage.addItemsInHashMap("tipKorisnika", "Primalac");
        Posiljke pp = new Posiljke(null, true);
        pp.setLocationRelativeTo(null);
        pp.setVisible(true);
    }//GEN-LAST:event_miPrimljenePosiljkeActionPerformed

    private void setComponents() {
        korisnik = (Korisnik) localStorage.getItemFromHashMap("korisnik");
        lbImePrezime.setText(korisnik.getImePrezime());
        lbTelefon.setText("Telefon: " + korisnik.getBrojTelefona().getBrojTelefona());
        lbAdresa.setText("Adresa: " + korisnik.getBrUlice().getAdresa().getPodaciAdresa().getNaziv() + " " + korisnik.getBrUlice().getBrojUlice());
        lbGrad.setText("Mesto: " + korisnik.getBrUlice().getMesto().getPodaciMesto().getNaziv() + " " + korisnik.getBrUlice().getMesto().getPodaciMesto().getPostanskiBroj());
    }

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JLabel lbAdresa;
    private javax.swing.JLabel lbGrad;
    private javax.swing.JLabel lbImePrezime;
    private javax.swing.JLabel lbTelefon;
    private javax.swing.JMenuItem miPoslatePosiljke;
    private javax.swing.JMenuItem miPrimljenePosiljke;
    // End of variables declaration//GEN-END:variables
}
