/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vreca;

import controller.Controller;
import domain.Adresnica;
import domain.DostavniSpisak;
import domain.PopisPosiljakaUSVreci;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import session.LocalStorage;
import tableModels.DostavniSpisakTableModel;
import tableModels.VrecaTableModel;

/**
 *
 * @author Vuk
 */
public class OptionsVreca extends javax.swing.JDialog {

    /**
     * Creates new form OptionsVreca
     */
    private LocalStorage localStorage = LocalStorage.getInstance();
    private List<PopisPosiljakaUSVreci> vrece;
    
    public OptionsVreca(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        vrece = new ArrayList<>();
        setComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSearchCriteria = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVrece = new javax.swing.JTable();
        btnCreateVreca = new javax.swing.JButton();
        btnUpdateVreca = new javax.swing.JButton();
        btnDeleteVreca = new javax.swing.JButton();
        btnViewVreca = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Pretraga vreća po šifri");

        txtSearchCriteria.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtSearchCriteria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchCriteriaKeyPressed(evt);
            }
        });

        tblVrece.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblVrece);

        btnCreateVreca.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCreateVreca.setText("Kreiraj vreću");
        btnCreateVreca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateVrecaActionPerformed(evt);
            }
        });

        btnUpdateVreca.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnUpdateVreca.setText("Ažuriraj vreću");
        btnUpdateVreca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateVrecaActionPerformed(evt);
            }
        });

        btnDeleteVreca.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnDeleteVreca.setText("Izbriši vreću");
        btnDeleteVreca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteVrecaActionPerformed(evt);
            }
        });

        btnViewVreca.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnViewVreca.setText("Pregled vreće");
        btnViewVreca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewVrecaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSearchCriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnViewVreca)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCreateVreca)
                                .addGap(57, 57, 57)
                                .addComponent(btnUpdateVreca)))
                        .addGap(57, 57, 57)
                        .addComponent(btnDeleteVreca)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSearchCriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateVreca)
                    .addComponent(btnUpdateVreca)
                    .addComponent(btnDeleteVreca))
                .addGap(18, 18, 18)
                .addComponent(btnViewVreca)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchCriteriaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchCriteriaKeyPressed
        // TODO add your handling code here:
        VrecaTableModel vrecaTableModel = (VrecaTableModel)tblVrece.getModel();
        List<PopisPosiljakaUSVreci> vreceModel = vrecaTableModel.getVrece();
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if(!txtSearchCriteria.getText().isEmpty()){
                List<PopisPosiljakaUSVreci> searchVrece = vreceModel.stream()
                                                .filter(vr->vr.getOznakaVrece()== Integer.parseInt(txtSearchCriteria.getText().trim()))
                                                .collect(Collectors.toList());
                tblVrece.setModel(new VrecaTableModel(searchVrece));
            }else{
                populateTable();
            }
        }
    }//GEN-LAST:event_txtSearchCriteriaKeyPressed

    private void btnCreateVrecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateVrecaActionPerformed
        // TODO add your handling code here:
        localStorage.addItemsInHashMap("operation", "CREATE");
        SaveVreca sv = new SaveVreca(null, true);
        sv.setLocationRelativeTo(null);
        sv.setVisible(true);
        localStorage.removeItemFromHashMap("operation");
        populateTable();
    }//GEN-LAST:event_btnCreateVrecaActionPerformed

    private void btnUpdateVrecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateVrecaActionPerformed
        // TODO add your handling code here:
        PopisPosiljakaUSVreci vreca = getSelectedVreca();
        if(vreca!=null){
            localStorage.addItemsInHashMap("operation", "UPDATE");
            localStorage.addItemsInHashMap("vreca", vreca);
            SaveVreca sv = new SaveVreca(null, true);
            sv.setLocationRelativeTo(null);
            sv.setVisible(true);
            localStorage.removeItemFromHashMap("operation");
            localStorage.removeItemFromHashMap("vreca");
            populateTable();
        }
    }//GEN-LAST:event_btnUpdateVrecaActionPerformed

    private void btnDeleteVrecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteVrecaActionPerformed
        // TODO add your handling code here:
        PopisPosiljakaUSVreci vreca = getSelectedVreca();
        if(vreca!=null){
            try {
                Controller.getInstance().deleteVreca(vreca);
                JOptionPane.showMessageDialog(this, "Uspešno ste izbrisali vreću");
                populateTable();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Exception", JOptionPane.PLAIN_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDeleteVrecaActionPerformed

    private void btnViewVrecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewVrecaActionPerformed
        // TODO add your handling code here:
        PopisPosiljakaUSVreci vreca = getSelectedVreca();
        if(vreca!=null){
            localStorage.addItemsInHashMap("vreca", vreca);
            PregledVrece pv = new PregledVrece(null, true);
            pv.setLocationRelativeTo(null);
            pv.setVisible(true);
            localStorage.removeItemFromHashMap("vreca");
            populateTable();
        }
    }//GEN-LAST:event_btnViewVrecaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateVreca;
    private javax.swing.JButton btnDeleteVreca;
    private javax.swing.JButton btnUpdateVreca;
    private javax.swing.JButton btnViewVreca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVrece;
    private javax.swing.JTextField txtSearchCriteria;
    // End of variables declaration//GEN-END:variables

    private void setComponents() {
        populateTable();
    }

    private void populateTable() {
        try {
            vrece = Controller.getInstance().getVrece(new PopisPosiljakaUSVreci());
            tblVrece.setModel(new VrecaTableModel(vrece));
        } catch (Exception ex) {
            Logger.getLogger(OptionsVreca.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private PopisPosiljakaUSVreci getSelectedVreca() {
        int selectedRow = tblVrece.getSelectedRow();
        if(selectedRow == -1){
            JOptionPane.showMessageDialog(this, "Niste izabrali vreću");
            return null;
        }else{
            return ((VrecaTableModel) tblVrece.getModel()).getVrece().get(selectedRow);
        }
    }
}
