/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vreca;

import controller.Controller;
import domain.Adresnica;
import domain.PopisPosiljakaUSVreci;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import posiljke.SavePosiljka;
import session.LocalStorage;
import tableModels.PosiljkaTableModel;

/**
 *
 * @author Vuk
 */
public class PregledVrece extends javax.swing.JDialog {

    /**
     * Creates new form PosiljkeVrece
     */
    private final LocalStorage localStorage = LocalStorage.getInstance();
    private final PopisPosiljakaUSVreci vreca;
    
    public PregledVrece(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        vreca = (PopisPosiljakaUSVreci) localStorage.getItemFromHashMap("vreca");
        setComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtOznakaVrece = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtOznakaSpiska = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMasaVrece = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPosiljkeVrece = new javax.swing.JTable();
        btnCreatePosiljka = new javax.swing.JButton();
        btnUpdatePosiljka = new javax.swing.JButton();
        btnDeletePosiljka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Podaci o Vreći sa pošiljkama");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Oznaka vreće");

        txtOznakaVrece.setEditable(false);
        txtOznakaVrece.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Oznaka spisak razmene");

        txtOznakaSpiska.setEditable(false);
        txtOznakaSpiska.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Masa vreće");

        txtMasaVrece.setEditable(false);
        txtMasaVrece.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel5.setText("Pošiljke vreće");

        tblPosiljkeVrece.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPosiljkeVrece);

        btnCreatePosiljka.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCreatePosiljka.setText("Kreiraj pošiljku");
        btnCreatePosiljka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePosiljkaActionPerformed(evt);
            }
        });

        btnUpdatePosiljka.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnUpdatePosiljka.setText("Ažuriraj pošiljku");
        btnUpdatePosiljka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePosiljkaActionPerformed(evt);
            }
        });

        btnDeletePosiljka.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnDeletePosiljka.setText("Izbriši pošiljku");
        btnDeletePosiljka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletePosiljkaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtOznakaVrece, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtOznakaSpiska, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtMasaVrece)))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnCreatePosiljka, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnUpdatePosiljka, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnDeletePosiljka, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtOznakaVrece, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtOznakaSpiska, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMasaVrece, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreatePosiljka, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdatePosiljka, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeletePosiljka, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreatePosiljkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePosiljkaActionPerformed
        // TODO add your handling code here:
        localStorage.addItemsInHashMap("operation", "CREATE-VRECA");
        SavePosiljka sp = new SavePosiljka(null, true);
        sp.setLocationRelativeTo(null);
        sp.setVisible(true);
        localStorage.removeItemFromHashMap("operation");
        setComponents();
    }//GEN-LAST:event_btnCreatePosiljkaActionPerformed

    private void btnUpdatePosiljkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePosiljkaActionPerformed
        // TODO add your handling code here:
        Adresnica posiljka = getSelectedPosiljka();
        if(posiljka!=null){
            localStorage.addItemsInHashMap("posiljka", posiljka);
            localStorage.addItemsInHashMap("operation", "UPDATE-VRECA");
            SavePosiljka sp = new SavePosiljka(null, true);
            sp.setLocationRelativeTo(null);
            sp.setVisible(true);
            localStorage.removeItemFromHashMap("posiljka");
            localStorage.removeItemFromHashMap("operation");
            setComponents();
        }
    }//GEN-LAST:event_btnUpdatePosiljkaActionPerformed

    private void btnDeletePosiljkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletePosiljkaActionPerformed
        // TODO add your handling code here:
        Adresnica posiljka = getSelectedPosiljka();
        if(posiljka!=null){
            String messageException;
            try {
                messageException = Controller.getInstance().deletePosiljka(posiljka);
                if(messageException==null){
                    JOptionPane.showMessageDialog(this, "Upesno izbrisana adresnica");
                }else{
                    JOptionPane.showMessageDialog(null, messageException, "Exception", JOptionPane.PLAIN_MESSAGE);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,ex.getMessage(), "Exception", JOptionPane.PLAIN_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDeletePosiljkaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreatePosiljka;
    private javax.swing.JButton btnDeletePosiljka;
    private javax.swing.JButton btnUpdatePosiljka;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPosiljkeVrece;
    private javax.swing.JTextField txtMasaVrece;
    private javax.swing.JTextField txtOznakaSpiska;
    private javax.swing.JTextField txtOznakaVrece;
    // End of variables declaration//GEN-END:variables

    private void setComponents() {
        try {
            PopisPosiljakaUSVreci vrecaDB = Controller.getInstance().getVreca(vreca);
            txtOznakaVrece.setText(vrecaDB.getOznakaVrece().toString());
            txtOznakaSpiska.setText(vrecaDB.getSpisak().getOznakaSpiska().toString());
            txtMasaVrece.setText(vrecaDB.getMasaVrece().toString());
            
            populateTable();
        } catch (Exception ex) {
            Logger.getLogger(PregledVrece.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void populateTable() {
        try {
            Adresnica adresnica = new Adresnica();
            adresnica.setVreca(vreca);
            List<Adresnica> posiljkeVrece = Controller.getInstance().getPosiljkeVrece(adresnica);
            tblPosiljkeVrece.setModel(new PosiljkaTableModel(posiljkeVrece));
        } catch (Exception ex) {
            Logger.getLogger(PregledVrece.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private Adresnica getSelectedPosiljka() {
        int selectedRow = tblPosiljkeVrece.getSelectedRow();
        if(selectedRow == -1){
            JOptionPane.showMessageDialog(this, "Niste izabrali posiljku");
            return null;
        }else{
            List<Adresnica> posiljke = ((PosiljkaTableModel) tblPosiljkeVrece.getModel()).getPosiljke();
            return posiljke.get(selectedRow);
        }
    }
}
