/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package linijevoznje;

import controller.Controller;
import domain.Vozac;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import session.LocalStorage;
import tableModels.VozacTableModel;

/**
 *
 * @author Vuk
 */
public class OptionsVozac extends javax.swing.JDialog {

    /**
     * Creates new form OptionsVozac
     */
    private final LocalStorage localStorage = LocalStorage.getInstance();
    private List<Vozac> vozaci;
    private Vozac vozac;
    
    public OptionsVozac(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        vozaci = new ArrayList<>();
        setComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblVozac = new javax.swing.JTable();
        btnCreateVozac = new javax.swing.JButton();
        btnUpdateVozac = new javax.swing.JButton();
        btnOptionsUpravljaLinijama = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblVozac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblVozac);

        btnCreateVozac.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCreateVozac.setText("Kreiraj Vozaca");
        btnCreateVozac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateVozacActionPerformed(evt);
            }
        });

        btnUpdateVozac.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnUpdateVozac.setText("Ažuriraj vozača");

        btnOptionsUpravljaLinijama.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnOptionsUpravljaLinijama.setText("Upravljanje linijama");
        btnOptionsUpravljaLinijama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOptionsUpravljaLinijamaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Vozači za prenos pošiljaka");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnCreateVozac, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnUpdateVozac, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(btnOptionsUpravljaLinijama, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(btnUpdateVozac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOptionsUpravljaLinijama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateVozac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOptionsUpravljaLinijamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOptionsUpravljaLinijamaActionPerformed
        // TODO add your handling code here:
        vozac = getSelectedVozac();
        if(vozac != null){
            localStorage.addItemsInHashMap("vozac", vozac);
            OptionsUpravlja ou = new OptionsUpravlja(null, true);
            ou.setLocationRelativeTo(null);
            ou.setVisible(true);
            localStorage.removeItemFromHashMap("vozac");
            populateTable();
        }
    }//GEN-LAST:event_btnOptionsUpravljaLinijamaActionPerformed

    private void btnCreateVozacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateVozacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateVozacActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateVozac;
    private javax.swing.JButton btnOptionsUpravljaLinijama;
    private javax.swing.JButton btnUpdateVozac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVozac;
    // End of variables declaration//GEN-END:variables

    private void setComponents() {
        populateTable();
    }

    private void populateTable() {
        try {
            vozaci = Controller.getInstance().getVozace(new Vozac());
            tblVozac.setModel(new VozacTableModel(vozaci));
        } catch (Exception ex) {
            Logger.getLogger(OptionsVozac.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private Vozac getSelectedVozac() {
        int selectedRow = tblVozac.getSelectedRow();
        if(selectedRow == -1){
            JOptionPane.showMessageDialog(this, "Niste izabrali vozača");
            return null;
        }else{
            return ((VozacTableModel) tblVozac.getModel()).getVozaci().get(selectedRow);
        }
    }
}
