/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package otpremnica;

import controller.Controller;
import domain.Adresnica;
import domain.DostavljanjePosiljke;
import domain.DostavniSpisak;
import domain.Korisnik;
import domain.Otpremnica;
import domain.Posta;
import domain.PostanskiRadnik;
import domain.Uplata;
import domain.Uplatnica;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import session.LocalStorage;

/**
 *
 * @author Vuk
 */
public class SaveOtpremnica extends javax.swing.JDialog {

    /**
     * Creates new form CreateOtpremnica
     */
    private LocalStorage localStorage = LocalStorage.getInstance();
    private final DostavniSpisak dostavniSpisak;
    private final PostanskiRadnik obracunskiRadnik;
    private final DostavljanjePosiljke dostavljenaPosiljka;
    private Korisnik uplatilac;
    private Korisnik posiljalac;
    private Adresnica posiljka;
    private Posta posta;
    private Uplatnica uplatnica;
    private Otpremnica otpremnica;
    private final String operation;
    
    public SaveOtpremnica(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        dostavniSpisak = (DostavniSpisak) localStorage.getItemFromHashMap("dostavniSpisak");
        dostavljenaPosiljka = (DostavljanjePosiljke) localStorage.getItemFromHashMap("posiljka");
        obracunskiRadnik = dostavniSpisak.getObracunskiRadnik();
        posta = obracunskiRadnik.getPosta();
        operation = (String) localStorage.getItemFromHashMap("operation");
        getData();
        setComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBrojUPL = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtObracunskiRadnik = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtOznakaDostavnogSpiska = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtUplatilac = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtIznos = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        cbPosta = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Podaci Otpremnica");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Broj UPL");

        txtBrojUPL.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Obračunski radnik");

        txtObracunskiRadnik.setEditable(false);
        txtObracunskiRadnik.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Oznaka dostavnog spiska");

        txtOznakaDostavnogSpiska.setEditable(false);
        txtOznakaDostavnogSpiska.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Uplatilac");

        txtUplatilac.setEditable(false);
        txtUplatilac.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtUplatilac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUplatilacActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Pošta");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Uplaćen iznos");

        txtIznos.setEditable(false);
        txtIznos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        btnSave.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSave.setText("Sačuvaj");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        cbPosta.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbPosta.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtOznakaDostavnogSpiska, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBrojUPL, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtObracunskiRadnik)
                                    .addComponent(cbPosta, 0, 195, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIznos, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUplatilac, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 43, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBrojUPL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtOznakaDostavnogSpiska, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtObracunskiRadnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbPosta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtUplatilac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtIznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            // TODO add your handling code here:
            otpremnica = getInputDataOtpremnice();
            String messageException;
            if(operation.equals("CREATE")){
                messageException = Controller.getInstance().addOtpremnica(otpremnica);
                if(messageException==null){
                    JOptionPane.showMessageDialog(this, "Uspesno ste kreirali otpremnicu");
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(null, messageException, "Exception", JOptionPane.PLAIN_MESSAGE);
                }
                
            }else if(operation.equals("UPDATE")){
                messageException = Controller.getInstance().updateOtpremnica(otpremnica);
                if(messageException==null){
                    JOptionPane.showMessageDialog(this, "Uspesno ste ažurirali otpremnicu");
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(null, messageException, "Exception", JOptionPane.PLAIN_MESSAGE);
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Exception", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtUplatilacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUplatilacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUplatilacActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<Posta> cbPosta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtBrojUPL;
    private javax.swing.JTextField txtIznos;
    private javax.swing.JTextField txtObracunskiRadnik;
    private javax.swing.JTextField txtOznakaDostavnogSpiska;
    private javax.swing.JTextField txtUplatilac;
    // End of variables declaration//GEN-END:variables

    private void getData() {
        try {
            posiljka = Controller.getInstance().getPosiljka(dostavljenaPosiljka.getPosiljka());
            uplatilac = dostavljenaPosiljka.getPrimalac();
            
            Uplata uplata = new Uplata();
            uplata.setKorisnik(dostavljenaPosiljka.getPrimalac());
            uplata.setPosiljka(dostavljenaPosiljka.getPosiljka());
            Uplata uplataDb = Controller.getInstance().getUplata(uplata);
            
            uplatnica = uplataDb.getUplatnica();
        } catch (Exception ex) {
            Logger.getLogger(SaveOtpremnica.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setComponents() {
        txtOznakaDostavnogSpiska.setText(dostavniSpisak.getOznakaDostavnogSpiska().toString());
        txtObracunskiRadnik.setText(obracunskiRadnik.getImePrezime());
        txtUplatilac.setText(uplatilac.getImePrezime());
        txtIznos.setText(uplatnica.getIznos().toString() + " " + "RSD");
        cbPosta.addItem(posta);
        cbPosta.setSelectedItem(posta);
        
        if(operation.equals("CREATE")){
            txtBrojUPL.setEditable(true);
        }else if(operation.equals("UPDATE")){
            populateForm();
        }
    }

    private Otpremnica getInputDataOtpremnice() {
        Integer brojUPL = Integer.parseInt(txtBrojUPL.getText());
        Integer iznos = uplatnica.getIznos();
        posta = (Posta) cbPosta.getSelectedItem();
        return new Otpremnica(brojUPL, iznos, obracunskiRadnik, dostavniSpisak, posiljka, posta);
    }

    private void populateForm() {
        try {
            List<Posta> poste = Controller.getInstance().getPoste(new Posta());
            otpremnica = (Otpremnica) localStorage.getItemFromHashMap("otpremnica");
            txtBrojUPL.setText(otpremnica.getBrojUPL().toString());
            cbPosta.setModel(new DefaultComboBoxModel(poste.toArray()));
            
            txtBrojUPL.setEditable(false);
            cbPosta.setEnabled(true);
            cbPosta.setSelectedItem(otpremnica.getPosta());
        } catch (Exception ex) {
            Logger.getLogger(SaveOtpremnica.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
