/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package postanskiradnik;

import domain.PostanskiRadnik;
import dostavnispisak.PostarDostavniSpisak;
import login.KorisnikLogin;
import login.RadnikLogin;
import session.LocalStorage;

/**
 *
 * @author Vuk
 */
public class Postar extends javax.swing.JDialog {

    /**
     * Creates new form Postar
     */
    private LocalStorage localStorage = LocalStorage.getInstance();
    private PostanskiRadnik postar;
    
    public Postar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        postar = (PostanskiRadnik) localStorage.getItemFromHashMap("postanski-radnik");
        setComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbImePrezime = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbNazivPoste = new javax.swing.JLabel();
        lbMesto = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miDostavniSpiskovi = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Poštar");

        lbImePrezime.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        lbImePrezime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbImePrezime.setText("jLabel2");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Radno mesto:");

        lbNazivPoste.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        lbNazivPoste.setText("jLabel3");

        lbMesto.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        lbMesto.setText("jLabel3");

        btnLogOut.setText("<-] Odjavite se");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        jMenu1.setText("Dostavni spisak");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        miDostavniSpiskovi.setText("Spisak");
        miDostavniSpiskovi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDostavniSpiskoviActionPerformed(evt);
            }
        });
        jMenu1.add(miDostavniSpiskovi);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbImePrezime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbMesto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbNazivPoste, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbImePrezime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbNazivPoste))
                .addGap(18, 18, 18)
                .addComponent(lbMesto)
                .addGap(26, 26, 26)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        RadnikLogin rl = new RadnikLogin(null, true);
        localStorage.removeItemFromHashMap("postanski-radnik");
        this.dispose();
        rl.setLocationRelativeTo(null);
        rl.setVisible(true);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void miDostavniSpiskoviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDostavniSpiskoviActionPerformed
        // TODO add your handling code here:
        PostarDostavniSpisak pds = new PostarDostavniSpisak(null, true);
        pds.setLocationRelativeTo(null);
        pds.setVisible(true);
    }//GEN-LAST:event_miDostavniSpiskoviActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbImePrezime;
    private javax.swing.JLabel lbMesto;
    private javax.swing.JLabel lbNazivPoste;
    private javax.swing.JMenuItem miDostavniSpiskovi;
    // End of variables declaration//GEN-END:variables

    private void setComponents() {
        lbImePrezime.setText(postar.getImePrezime());
        lbNazivPoste.setText(postar.getPosta().getNaziv());
        lbMesto.setText(postar.getPosta().getMesto().getPodaciMesto().getNaziv() + " " + postar.getPosta().getMesto().getPodaciMesto().getPostanskiBroj());
    }
}
