/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package korisnik.posiljka;

import controller.Controller;
import domain.Adresnica;
import domain.DostavljanjePosiljke;
import domain.Korisnik;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import session.LocalStorage;
import tableModels.PoslatePosiljkeTableModel;
import tableModels.PrimljenePosiljkeTableModel;

/**
 *
 * @author Vuk
 */
public class Posiljke extends javax.swing.JDialog {

    /**
     * Creates new form PosiljkaPrimljeno
     */
    
    private LocalStorage localStorage;
    private Korisnik korisnik;
    
    public Posiljke(java.awt.Frame parent, boolean modal){
        super(parent, modal);
        initComponents();
        localStorage = LocalStorage.getInstance();
        korisnik = (Korisnik) localStorage.getItemFromHashMap("korisnik");
        setComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrimljenePosiljke = new javax.swing.JTable();
        lbNaslov = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblPrimljenePosiljke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPrimljenePosiljke);

        lbNaslov.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lbNaslov.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNaslov.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNaslov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbNaslov)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    lbNaslovam args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbNaslov;
    private javax.swing.JTable tblPrimljenePosiljke;
    // End of variables declaration//GEN-END:variables

    private void setComponents() {
        String tipKorisnika = (String) localStorage.getItemFromHashMap("tipKorisnika");
        if(tipKorisnika.equals("Primalac")){
            setTableComponentPrimalac();
        }
        else{
            setTableComponentPosiljalac();
        }
    }

    private void setTableComponentPrimalac() {
        lbNaslov.setText("Primljene pošiljke korisnika - " + korisnik.getImePrezime());
        try {
            DostavljanjePosiljke dp = new DostavljanjePosiljke();
            dp.setPrimalac(korisnik);
            List<DostavljanjePosiljke> primljenePosiljke = Controller.getInstance().getPrimljenePosiljkeKorisnika(dp);
            tblPrimljenePosiljke.setModel(new PrimljenePosiljkeTableModel(primljenePosiljke));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
    
    private void setTableComponentPosiljalac(){
        lbNaslov.setText("Poslate pošiljke korisnika - " + korisnik.getImePrezime());
        try {
            List<Adresnica> poslatePosiljke = Controller.getInstance().getPosiljke(new Adresnica());
            tblPrimljenePosiljke.setModel(new PoslatePosiljkeTableModel(poslatePosiljke.stream()
                    .filter(poslataPosiljka->poslataPosiljka.getPosiljalac().getJmbg().equals(korisnik.getJmbg()))
                    .collect(Collectors.toList())));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
}
