/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package posiljke;

import controller.Controller;
import domain.*;
import java.io.IOException;
import java.util.List;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import session.LocalStorage;

/**
 *
 * @author Vuk
 */
public class SavePosiljka extends javax.swing.JDialog {

    /**
     * Creates new form CreatePosiljka
     */
    private LocalStorage localStorage = LocalStorage.getInstance();
    private Adresnica adresnica;
    private List<Korisnik> korisnici;
    private Korisnik primalac;
    private Korisnik posiljalac;
    private List<PopisPosiljakaUSVreci> vrece;
    private List<SpisakRazmene> spiskovi;
    private PopisPosiljakaUSVreci vreca;
    private SpisakRazmene spisak;
    private final String operation;
    
    public SavePosiljka(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        operation = (String) localStorage.getItemFromHashMap("operation");
        setComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSifraAdresnice = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSadrzina = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNapomena = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbPrimalac = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbPosiljalac = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbVreca = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbSpisak = new javax.swing.JComboBox<>();
        btnClearForm = new javax.swing.JButton();
        btnSavePosiljka = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtMasa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Sifra pošiljke");

        txtSifraAdresnice.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Sadržina");

        txtSadrzina.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Napomena");

        txtNapomena.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Podaci Pošiljka");

        jLabel5.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Podaci korisnika");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Primalac");

        cbPrimalac.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Pošiljalac");

        cbPosiljalac.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Vreća pošiljaka");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Vreća");

        cbVreca.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbVreca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbVrecaItemStateChanged(evt);
            }
        });
        cbVreca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbVrecaActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Spisak Razmene");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Spisak");

        cbSpisak.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cbSpisak.setForeground(new java.awt.Color(255, 255, 255));
        cbSpisak.setEnabled(false);

        btnClearForm.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnClearForm.setText("Očisti polja");
        btnClearForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearFormActionPerformed(evt);
            }
        });

        btnSavePosiljka.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSavePosiljka.setText("Sačuvaj");
        btnSavePosiljka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePosiljkaActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("Masa");

        txtMasa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSifraAdresnice, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSadrzina, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNapomena, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMasa, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(btnSavePosiljka, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnClearForm, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbPrimalac, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbPosiljalac, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbVreca, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(cbSpisak, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(51, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSifraAdresnice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSadrzina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNapomena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtMasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbPrimalac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbPosiljalac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbVreca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbSpisak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClearForm, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSavePosiljka, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSavePosiljkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePosiljkaActionPerformed
        // TODO add your handling code here:
        primalac = getInputDataPrimalac();
        posiljalac = getInputDataPosiljalac();
        vreca = getInputDataVreca();
        spisak = getInputDataSpisak();
        adresnica = getInputDataAdresnica();
        
        try{
            String messageException;
            if(!primalac.equals(posiljalac)){
                if(operation.equals("CREATE") || operation.contains("CREATE-VRECA")){
                    messageException = Controller.getInstance().addPosiljka(adresnica);
                    if(messageException==null){
                        JOptionPane.showMessageDialog(this, "Upesno kreirana adresnica");
                        this.dispose();
                    }else{
                        JOptionPane.showMessageDialog(null, messageException, "Exception", JOptionPane.PLAIN_MESSAGE);
                    }
                }else if(operation.equals("UPDATE") || operation.contains("UPDATE-VRECA")){
                    messageException = Controller.getInstance().updatePosiljka(adresnica);
                    if(messageException==null){
                        JOptionPane.showMessageDialog(this, "Upesno ažurirana adresnica");
                        this.dispose();
                    }
                    else{
                        JOptionPane.showMessageDialog(null, messageException, "Exception", JOptionPane.PLAIN_MESSAGE);
                    }
                }
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Exception", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_btnSavePosiljkaActionPerformed

    private void btnClearFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearFormActionPerformed
        // TODO add your handling code here:
        txtSifraAdresnice.setText("");
        txtNapomena.setText("");
        txtSadrzina.setText("");
    }//GEN-LAST:event_btnClearFormActionPerformed

    private void cbVrecaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbVrecaItemStateChanged

    }//GEN-LAST:event_cbVrecaItemStateChanged

    private void cbVrecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbVrecaActionPerformed
        // TODO add your handling code here:
        PopisPosiljakaUSVreci v = (PopisPosiljakaUSVreci) cbVreca.getSelectedItem();
        List<SpisakRazmene> s = spiskovi.stream()
                                        .filter(sp->Objects.equals(sp.getOznakaSpiska(), v.getSpisak().getOznakaSpiska()))
                                        .collect(Collectors.toList());
        cbSpisak.setSelectedItem(s.get(0));
    }//GEN-LAST:event_cbVrecaActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearForm;
    private javax.swing.JButton btnSavePosiljka;
    private javax.swing.JComboBox<Korisnik> cbPosiljalac;
    private javax.swing.JComboBox<Korisnik> cbPrimalac;
    private javax.swing.JComboBox<SpisakRazmene> cbSpisak;
    private javax.swing.JComboBox<PopisPosiljakaUSVreci> cbVreca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtMasa;
    private javax.swing.JTextField txtNapomena;
    private javax.swing.JTextField txtSadrzina;
    private javax.swing.JTextField txtSifraAdresnice;
    // End of variables declaration//GEN-END:variables

    private void setComponents() {
        try {
            vrece = Controller.getInstance().getVrece(new PopisPosiljakaUSVreci());
            spiskovi = Controller.getInstance().getSpiskoviRazmene(new SpisakRazmene());
            korisnici = Controller.getInstance().getKorisnici(new Korisnik());
            
            cbVreca.setEnabled(true);
            cbVreca.setModel(new DefaultComboBoxModel(vrece.toArray()));
            cbSpisak.setModel(new DefaultComboBoxModel(spiskovi.toArray()));
            cbPrimalac.setModel(new DefaultComboBoxModel(korisnici.toArray()));
            cbPosiljalac.setModel(new DefaultComboBoxModel(korisnici.toArray()));
            
            PopisPosiljakaUSVreci vr = (PopisPosiljakaUSVreci) cbVreca.getSelectedItem();
            cbSpisak.setSelectedItem(vr.getSpisak());
            
            if(operation.equals("UPDATE") || operation.equals("UPDATE-VRECA")){
                populateForm();
            }else if(operation.equals("CREATE-VRECA")){
                populateFormFromVreca();
            }
            
        } catch (Exception ex) {
            Logger.getLogger(SavePosiljka.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void populateForm() {
        adresnica = (Adresnica) localStorage.getItemFromHashMap("posiljka");
        txtSifraAdresnice.setText(adresnica.getSifraAdresnice().toString());
        txtSifraAdresnice.setEnabled(false);
        txtSifraAdresnice.setEditable(false);
        txtNapomena.setText(adresnica.getNapomena());
        txtSadrzina.setText(adresnica.getSadrzina());
        txtMasa.setText(adresnica.getMasa().toString());
        cbPosiljalac.setSelectedItem(adresnica.getPosiljalac());
        cbPrimalac.setSelectedItem(adresnica.getPrimalac());
        cbVreca.setSelectedItem(adresnica.getVreca());
        cbSpisak.setSelectedItem(adresnica.getSpisak());
        
        if(operation.equals("UPDATE-VRECA")){
            cbVreca.setEnabled(false);
        }
        else{
            cbVreca.setEnabled(true);
        }
    }

    private Korisnik getInputDataPrimalac() {
        return (Korisnik) cbPrimalac.getSelectedItem();
    }

    private Korisnik getInputDataPosiljalac() {
        return (Korisnik) cbPosiljalac.getSelectedItem();
    }

    private PopisPosiljakaUSVreci getInputDataVreca() {
        return (PopisPosiljakaUSVreci) cbVreca.getSelectedItem();
    }

    private SpisakRazmene getInputDataSpisak() {
        return (SpisakRazmene) cbSpisak.getSelectedItem();
    }

    private Adresnica getInputDataAdresnica() {
        Integer sifraAdresnice = Integer.parseInt(txtSifraAdresnice.getText());
        String napomena = txtNapomena.getText();
        String sadrzina = txtSadrzina.getText();
        Integer masa = Integer.parseInt(txtMasa.getText());
        return new Adresnica(sifraAdresnice, vreca, spisak, posiljalac, primalac, masa, napomena, sadrzina);
    }

    private void populateFormFromVreca() {
        vreca = (PopisPosiljakaUSVreci) localStorage.getItemFromHashMap("vreca");
        cbVreca.setSelectedItem(vreca);
        cbVreca.setEnabled(false);
        cbSpisak.setSelectedItem(vreca.getSpisak());
        cbSpisak.setEnabled(false);
    }
}
